- name: Deploy Web Application
  hosts: servers
  become: true

  tasks:
    - name: Create project directory
      file:
        path: /opt/my-app
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: files/docker-compose.yml
        dest: /opt/my-app/docker-compose.yml

    - name: Copy prometheus config file
      copy:
        src: files/prometheus.yml
        dest: /opt/my-app/prometheus.yml
        mode: '0644'

    - name: Copy htpasswd file
      copy:
        src: files/.htpasswd
        dest: /opt/my-app/.htpasswd
        mode: '0644'

    - name: Copy nginx config
      copy:
        src: files/nginx.conf
        dest: /opt/my-app/nginx.conf
        mode: '0644'
      notify: Restart Nginx

    # --- !!! ВОТ ЗДЕСЬ ИЗМЕНЕНИЯ !!! ---
    # Мы удаляем старый блок 'shell' и ставим этот:
    
    - name: Start services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/my-app   # Где лежит файл
        pull: always               # <--- САМОЕ ВАЖНОЕ: Всегда скачивать свежий образ!
        state: present             # Убедиться, что контейнеры запущены
    
    # --- КОНЕЦ ИЗМЕНЕНИЙ ---

  handlers:
    - name: Restart Nginx
      community.docker.docker_container:
        name: my-production-site
        state: started
        restart: yes
